### PR TITLE
Feat: Edit Control to Tweets

### PR DESCRIPTION
**Pull request by ryzizub**
I have implemented edit history option to tweets based on the https://developer.twitter.com/en/docs/twitter-api/v1/edit-tweets.

Let me know if you find any issues or questions in code @robertodoering

### CODE REVIEW

**Review by robertodoering — APPROVED** [review]
Looks great, thank you!

**Comment by ryzizub** [comment]
@robertodoering awesome! Would be good to create new release soon 😊 Any plans?

**Comment by robertodoering** [comment]
@ryzizub I just published the changes with version 0.5.7 :)

**Comment by ryzizub** [comment]
> @ryzizub I just published the changes with version 0.5.7 :)

Thank you 👍

**Pull request merged**
